### PR TITLE
Scrum 141 - reservation history and things

### PR DESCRIPTION
**Pull request by denialpan**
@weswilson24 sorry for creating this so late, i thought i created a pr

### CODE REVIEW

**Comment by weswilson24** [comment]
The view details and view damage report should be clickable buttons. I can change this in my modal code or you ca n change it here

**Comment by mengzhuou** [comment]
image
Not sure why it looks like this on my page. But it doesn't look like what Figma required. Could you explain in the description for your changes with some pictures or a video?

**Comment by denialpan** [comment]
@mengzhuou Untitled
Here is the design from Jira. Here is a quick video, very bad quality to keep it under 10mb

https://github.com/user-attachments/assets/70eb9aa5-abf4-4cbf-b3ef-db3245b9a117

**Comment by weswilson24** [comment]
Me and Daniel just talked. Due to the structure of the backend Damage Report doesnt have a orderNumber value so its not possible to tell which damageReport should go with which orderNumber. The correct damage reprot cant be mapped and you also cant tell if that order has a damage report associated with it. Other than that i think its ready to go

**Review by weswilson24 — APPROVED** [review]

**Review by Xisheng0725 — APPROVED** [review]

**Pull request merged**
