### PR TITLE
Scrum 176 : add TA site

### PR DESCRIPTION
**Pull request by Xisheng0725**
image
image

### CODE REVIEW

**Review by Qihuiwang3 — APPROVED** [review]
looks good to me

**Comment by mengzhuou** [comment]
image
image


TA role's entering page after Login is not Select Task. Is this intended?

**Review by mengzhuou — APPROVED** [review]

**Comment by Xisheng0725** [comment]
> image image
> TA role's entering page after Login is not Select Task. Is this intended?

Yeah, I feel like TA is also students, but they can get in admin site throght the side bar

**Comment by Xisheng0725** [comment]
> image image
> TA role's entering page after Login is not Select Task. Is this intended?

Qihui said they should go to admin

**Pull request merged**
