### PR TITLE
Scrum email (Scrum 161 and 119)

### PR DESCRIPTION
**Pull request by weswilson24**
This creates a send Announcement button for an admin that send the message to all users emails in the database. This also makes an automatic email when a purchase is completed to the users email.

What you need to do:

In the backend .env file, copy and paste this code 

EMAIL_USERNAME=dickenscharles758@gmail.com
EMAIL_PASSWORD=hhvk qbfx paik bnae

Its a temporary email and password that is needed in order for this to work. The password is a specific App password setup, so using your email and password here wouldnt work use these two. 

In the file labeled SendAnnounce.js under the modal section on the frontend, there is a const called SendAnnounce and then a line of code called sendEmail. In that code should be a placeholder for the email address for the email to be sent to currentyl being "testemail" Change this to any email that you have access to as a string. This will be where the email will be sent to once the send announcement button is pressed. I currently have the actual code commented out to send out an email to all students in the database because I dont want to spam those emails for testing.

For the automatic email when a purchase is made, make sure that the email under the account you make the order with is an email you have access to. It will automatically be sent to the email under that account that made the order. 

Finally you need to do npm install nodemailer for the backend

How to access SendAnnoucnement Button:  Log in as an admin, got to the view reservations page, and click the button. 

How to see automatic email. Sign in, create a cart, and then pay through paypal. Once the payment is confirmed it will have the same generated oorder number and bar code as the last page.

Screenshot 2024-10-31 155909

### CODE REVIEW

**Comment by mengzhuou** [comment]
It should send out email for professor evenif they do not make a PayPal payment.

**Review by Qihuiwang3 — CHANGES_REQUESTED** [review]
I got the auto-generated email in my mailbox, but I didn't get "send announcement" to work. Nothing happened after I click the button.

**Comment by weswilson24** [comment]
@Qihuiwang3 did you go into the SendAnnounce modal and change the text to an email you have access to? 
image
Change the value of to: to your personal email for testing purposes it have it working on my end for that

**Comment by Qihuiwang3** [comment]
@weswilson24  I am pretty sure I did.... Let me try it one more time before our meeting at 5, if i still can't get it to work, we can talk about this in the meeting today!

**Review by Qihuiwang3 — APPROVED** [review]
It works on my end!

**Review by Xisheng0725 — APPROVED** [review]

**Pull request merged**
