### PR TITLE
Scrum 207 - Added correct cancel and extend order modals 

### PR DESCRIPTION
**Pull request by weswilson24**
Added modals to cancel and extend order.

Extend: Button can only be pushed if it hasnt been extended once or past date

Cancel: Cancel button can always be pressed, but if within 24 hours no confirm button shows up on modal, if outside of 24 hours the confirm button does show up

### CODE REVIEW

**Review by Qihuiwang3 — CHANGES_REQUESTED** [review]
2 things about the alert:
1. Extension: 
Screenshot 2024-11-21 at 13 22 50
It seems like the first alert is still on the screen, and second alert is covered on top of it. Can you remove the first alert when second alert pop up?

2. Cancel:
I feel like the current alert should pop up when users can't cancel the reservation (when the button is gray) to inform them they cannot cancel it because the pick up time is less than 24 hours. Change the wording to this will make more sense:
Screenshot 2024-11-21 at 13 35 25

and when the button is not gray, you could do a pop up alert like this:
Screenshot 2024-11-21 at 13 31 27

**Comment by Qihuiwang3** [comment]
Also, we cannot merge 182 or 182-error because there are still bugs from Daniel's previous work, so if we want to merge this PR, how can we do it then?

**Comment by mengzhuou** [comment]
1. After making an order and checked out the equipment, the reservation details popup does not have itemID displayed.
image

2. In reservation history page, these buttons are all non-clickable for me.
image

**Comment by weswilson24** [comment]
> 1. After making an order and checked out the equipment, the reservation details popup does not have itemID displayed.
> 
> image
> 2. In reservation history page, these buttons are all non-clickable for me.
> 
> image

ill look at the itemID tonight. In terms of the two buttons, the buttons should look like that if the item has already been checked in

**Comment by weswilson24** [comment]
Made a slight change for itemID code its working on my end now
image
image

**Review by Qihuiwang3 — APPROVED** [review]

**Pull request closed without merging**
