### PR TITLE
Scrum 147- UI for Class Codes Admin Page

### PR DESCRIPTION
**Pull request by weswilson24**
Screenshot 2024-10-18 183813
http://localhost:3000/ClassCodes
Fixed UI issues for previous page.

Issues from Jira:
1.Uses standard styling for table now
2.Both edit and add modal pop up and cna create/edit info
3.New class gets added to the top of the list
4.Deleted page so its only one
5.Buttons in correct place
6.All columns exist

### CODE REVIEW

**Review by Qihuiwang3 — COMMENTED** [review]
1. Seems like "Search by Class" text is missing in the search bar when I didn't click the box.  
image
2. The **"Class"** Column, Is it possible to make it look more like the design on Figma? The space between the icon and the text should be a bit larger, and the icon could be slightly shrunk to match the height of the text. This way, it will look more cohesive and unified.
image
3. The **Edit/Add New Class Code modal** appears to have a scroll bar on the right side, which doesn’t seem to be present in other modals. I’m not sure why that’s happening.
Also, for the **Select Equipment for this Class section**, the current design feels a bit off. Instead of having two boxes (one on top and one on the bottom), maybe we could simplify it by having just one box. Initially, before the user makes any selection, the placeholder text could say“Select Equipment.” Once the user has made their selection, the selected equipment name(s) would replace that placeholder. We could also adjust the placeholder text to say “Select all equipment that apply.” Let me know your thoughts on this.
image
4. Edit Class Code Modal:
When users try to edit classes, it seems they are unable to remove any of the selected equipment. They can only add new equipment from the list. Additionally, if a user didn’t create a bundle when they initially created the class code and later wants to fix it, they are unable to modify the Package ID, though they can edit the other fields.
After changing the package name, price, and selecting some equipment from the list, I noticed that clicking the “Save” button doesn’t seem to work, and no action occurs afterward. We might want to fix the functionality here.

**Comment by weswilson24** [comment]
Did you pull a while ago and just now looked at it? Cause my first push had the Search bar empty and scrolll bar but my next push fixed that. On my end it shows Search By Class and no scroll bar. Also on my end if i select package name, price and equipment it still lets me save. Ill go in and add the ability to delete items and see what i can do about making it one row

**Comment by Qihuiwang3** [comment]
> Did you pull a while ago and just now looked at it? Cause my first push had the Search bar empty and scrolll bar but my next push fixed that. On my end it shows Search By Class and no scroll bar. Also on my end if i select package name, price and equipment it still lets me save. Ill go in and add the ability to delete items and see what i can do about making it one row

I pulled it right before I take a look at it. Let me pull it again, and make sure I am seeing right thing

**Comment by Qihuiwang3** [comment]
> > Did you pull a while ago and just now looked at it? Cause my first push had the Search bar empty and scrolll bar but my next push fixed that. On my end it shows Search By Class and no scroll bar. Also on my end if i select package name, price and equipment it still lets me save. Ill go in and add the ability to delete items and see what i can do about making it one row
> 
> I pulled it right before I take a look at it. Let me pull it again, and make sure I am seeing right thing

Yeah.. the search bar is empty, and the scroll bar is still there

**Comment by weswilson24** [comment]
Maybe try repulling it now? See if the latest commit to fix letter spacing shows up in the class column

**Comment by Qihuiwang3** [comment]
> Maybe try repulling it now? See if the latest commit to fix letter spacing shows up in the class column. It would be weird if that one shows up as a change but the others dont for some reason

I just tried, nothing has changed 🥲

**Comment by Qihuiwang3** [comment]
> > Maybe try repulling it now? See if the latest commit to fix letter spacing shows up in the class column. It would be weird if that one shows up as a change but the others dont for some reason
> 
> I just tried, nothing has changed 🥲

@denialpan @mengzhuou @Xisheng0725 
Can you guys please try it?

**Comment by weswilson24** [comment]
This is how it currently looks and operates on my end 
[Recording-20241020_121144.webm](https://github.com/user-attachments/assets/1de8d2a8-c635-4752-8909-cc33f2e505ef)

**Comment by mengzhuou** [comment]
1. Input width should be the same: 
image

2. Price input should be by default 0 and cannot accept non-numeric input. 
http://localhost:3000/equipment
You can use the equipment popup modal as a reference.
image

**Comment by weswilson24** [comment]
[
[Recording-20241020_161829.webm](https://github.com/user-attachments/assets/d904fba7-9790-4103-9e85-3605038b4b0c)

**Review by Qihuiwang3 — APPROVED** [review]

**Review by Xisheng0725 — APPROVED** [review]

**Pull request merged**
