### PR TITLE
Scrum  143/144  Student Damage Popup Modals from Orders

### PR DESCRIPTION
**Pull request by weswilson24**
After the completion of the reservationHistory table from Daniel i noticed there was no value to get from it that could map to a specific Damage report. So the mongoDB for Damage Report needs to be changed to have an OrderNumber as a value. Thats the only change needed right there, as once thats implemented it will only change one line of code which is the fetch singelDamageReport through the code i get through the reservationHistoryTable, so right now i just have it set to one of the database items until it can get mapped. BarCode could get mapped to the orderNumber, so it works fine 
[Recording-20241020_220605.webm](https://github.com/user-attachments/assets/93aedd24-3da0-4803-9e00-177435745413)

### CODE REVIEW

**Review by Xisheng0725 — CHANGES_REQUESTED** [review]
run time error:
ERROR in ./src/components/Pages/ReservationConfirmationMessagePage/ReservationConfirmationMessagePage.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/xishengzhang/Desktop/JID-4121-LMCFilm/frontend/src/components/Pages/ReservationConfirmationMessagePage/ReservationConfirmationMessagePage.js: Identifier 'useNavigate' has already been declared. (7:9)

   5 | import Barcode from 'react-barcode';
   6 | import Button from '../../Button/Button';
>  7 | import { useNavigate } from "react-router-dom";
     |          ^
   8 | import { useLocation } from 'react-router-dom';
   9 |
  10 | function ReservationConfirmationMessagePage() {

**Comment by weswilson24** [comment]
Thats from one of Daniels commits. I reverted that file back to the one on the main branch. Idk if i should push the main branch of that file back or keep the one Daniel changed @Xisheng0725

**Comment by Xisheng0725** [comment]
> Thats from one of Daniels commits. I reverted that file back to the one on the main branch. Idk if i should push the main branch of that file back or keep the one Daniel changed @Xisheng0725

I think it's because dulicate import, I think just need to delete one

**Comment by weswilson24** [comment]
yeah looks like duplicate ill fix it

**Review by Xisheng0725 — APPROVED** [review]

**Review by Qihuiwang3 — APPROVED** [review]

**Pull request merged**
