### PR TITLE
Scrum 182 errors found and fixed

### PR DESCRIPTION
**Pull request by weswilson24**
First error: Somehow the admin would be sent two emails instead of one when confirming order with new code, made it so only one would be sent now through a checking system

Second Error. Reserbation history table didnt properly update when cancel order and extend order were selected. Fixed

Third change (not error): More quality of life update- Disabled done button in extend order until both date and time are selected

### CODE REVIEW

**Comment by mengzhuou** [comment]
I just made an order, it appears only once. However, my order was assigned with itemID when making the order instead of storing itemID while checking out the equipments. 
image

**Comment by weswilson24** [comment]
> I just made an order, it appears only once. However, my order was assigned with itemID when making the order instead of storing itemID while checking out the equipments. image

I fixed the itemID not to show in my scrum-207 branch if you want to test that

**Comment by mengzhuou** [comment]
> > I just made an order, it appears only once. However, my order was assigned with itemID when making the order instead of storing itemID while checking out the equipments. image
> 
> I fixed the itemID not to show in my scrum-207 branch if you want to test that

Okay in that case I will approve this PR

**Review by mengzhuou — APPROVED** [review]

**Comment by mengzhuou** [comment]
So I just cleared the database and created an order. The order is made twice with different order number and I got 2 orders instead of 1.

**Review by mengzhuou — CHANGES_REQUESTED** [review]
So I just cleared the database and created an order. The order is made twice with different order number so I got 2 orders instead of 1.

**Comment by weswilson24** [comment]
You didnt need to change anything in the payment page after my commits. the changes in payment after merge from main did something to create two orders when my code already made it create one order

**Pull request merged**
