### PR TITLE
scrum-127: add react redux from enter class code to checkout page

### PR DESCRIPTION
**Pull request by Xisheng0725**
I talked to Daniel, He will handle the cart data passing using react since we have sprint 1 bug fix ticket, please using 54321 as the code to testing or you can create your own code, right now All the feature are using real DB

### CODE REVIEW

**Comment by mengzhuou** [comment]
1. Could you please make sure vertical and horizontal scroll bar do not appear on these pages:
http://localhost:3000/SelectClass
http://localhost:3000/ReservationPage

image
2. These two button color seem not match: 
image
3. When clicking on Back button, instead of going back to entercode page, I was redirected to Reservation page.

**Comment by weswilson24** [comment]
A deleteClassCode function that accesses is needed as well

**Comment by Xisheng0725** [comment]
> A deleteClassCode function that accesses is needed as well

already add deleted, please review it again

**Review by mengzhuou — CHANGES_REQUESTED** [review]
1. I see you improved css, but it does not seem to match with the style of the previous page when to go back. Buttons are located more in the bottom in first page but located in almost the middle in second page.
image


image

2. Then if I dropdown the item, it extends to the bottom of the page which is not reachable. Maybe we need to adjust the size of component to make it fit. 
image

**Review by mengzhuou — APPROVED** [review]

**Review by Qihuiwang3 — APPROVED** [review]
The functionalities are all working correctly.

**Pull request merged**
