### PR TITLE
Scrum 169: minor fixes to reservation history page

### PR DESCRIPTION
**Pull request by denialpan**
- fixes reservation history table first column to show the code
- route back button to be instead of the last page user was on

for the style of the buttons for back and announcement buttons, they have the same css styling as the rest of the page already

### CODE REVIEW

**Comment by mengzhuou** [comment]
image
The width for first column is too wide and too narrow for 4th column. Maybe we should adjust that? Others look good so I approved

**Review by mengzhuou — APPROVED** [review]

**Review by Xisheng0725 — CHANGES_REQUESTED** [review]
please adjust the width like Nina mentioned before

**Review by Qihuiwang3 — CHANGES_REQUESTED** [review]
I got this error
image

**Comment by denialpan** [comment]
@Qihuiwang3 I don't seem to get this error on that page, am unsure how to get to that.

image

**Review by Qihuiwang3 — APPROVED** [review]

**Review by Xisheng0725 — APPROVED** [review]

**Pull request merged**
