### PR TITLE
[DONT MERGE] scrum-182: Fix to make only one order

### PR DESCRIPTION
**Pull request by denialpan**
Fixes previous merge problem to only make one order instead of two.

Addresses multiple tickets at the same time:

scrum-182
198
196
171

in progress:
167

### CODE REVIEW

**Comment by mengzhuou** [comment]
1. I have these errors in the backend when making the order
image

2. Order number is not found for what's displayed on the QR code page versus what's on our database
3. Could you please merge from the main? I understand that there's no merge conflict but this will be helpful for testing purpose.

**Review by Xisheng0725 — CHANGES_REQUESTED** [review]
image
available equipment has no equipment show even if the class code contain items

**Review by Xisheng0725 — CHANGES_REQUESTED** [review]
please fetch to the latest main, compare with main branch, the time selection is differentwith main branch:

image

**Comment by mengzhuou** [comment]
Order created only once is successful!

Same to Evan's comment, please merge the most updated main code so that the date user can pick is 5 days only. For more details you can checkout his closed PR or jira ticket.
image

**Review by Qihuiwang3 — CHANGES_REQUESTED** [review]
1. After a reservation is being made, there are two exact orders display in the reservation history page, BUT, with different order number (bar code number).
2. When the order has been made successfully, the cart didn't empty. EVEN IF i select another class, the same exact equipment still shows in my cart.
3. view details modal + view damage report modal needs to be connected as well. This was the ticket from last sprint. Also the UI of the damage report can be found in Figma

**Comment by denialpan** [comment]
@mengzhuou @Xisheng0725 for the time selection picker, did the client specifically say that reservation starting dates should only be possible within 5 days of the current date, or that the distance between the reservation pickup and checkout dates should be at most 5 days apart. Also for git fetch, there is no git fetch from main to solve this one, since I accidentally removed that code from a previous sprint, so I'm writing it again.

**Comment by Xisheng0725** [comment]
> @mengzhuou @Xisheng0725 for the time selection picker, did the client specifically say that reservation starting dates should only be possible within 5 days of the current date, or that the distance between the reservation pickup and checkout dates should be at most 5 days apart. Also for git fetch, there is no git fetch from main to solve this one, since I accidentally removed that code from a previous sprint, so I'm writing it again.

if you run the main branch, and play arount the time, you will know what I mean by 5 days

**Comment by denialpan** [comment]
@Qihuiwang3 Two orders will always be made since that's how `useEffect()` works in development. When the page is in production, it will only run once. To test that an order is only made once, comment out `<React.StrictMode>` in `index.js` can be commented out, leaving only `<App.js>`.

**Comment by denialpan** [comment]
@Xisheng0725 Pushed changes to reflect that.

**Comment by Qihuiwang3** [comment]
> @mengzhuou @Xisheng0725 for the time selection picker, did the client specifically say that reservation starting dates should only be possible within 5 days of the current date, or that the distance between the reservation pickup and checkout dates should be at most 5 days apart. Also for git fetch, there is no git fetch from main to solve this one, since I accidentally removed that code from a previous sprint, so I'm writing it again.

Client said the distance between the reservation pickup and checkout dates should be at most 5 days apart, and I am actually have a meeting with him this afternoon to discuss about the logic of the date selection. What's your question about this? Is this related to something that you are currently working on? Also I don't really understand what you have removed from the previous sprint.

**Comment by Qihuiwang3** [comment]
> @Qihuiwang3 Two orders will always be made since that's how `useEffect()` works in development. When the page is in production, it will only run once. To test that an order is only made once, comment out `<React.StrictMode>` in `index.js` can be commented out, leaving only `<App.js>`.

So why is this happening? why can't you comment out `<React.StrictMode>` in `index.js`? I am worried that this functionality will not work if two orders show up after deployment.

**Comment by Xisheng0725** [comment]
> when you change the date/time on /ReservationPage, and go back, the date/time should also be updated. you didn't fix the merge conflict issue from sprint3

when you change the date/time on /ReservationPage, and go back, the date/time should also be updated. you didn't fix the merge conflict issue from sprint3

**Comment by denialpan** [comment]
@Qihuiwang3 Was confused on whether the date limitations would be from starting at the current date, so from today and 5 days ahead are the only selectable pick up and return days. That's the version from main, which I pushed already, but originally I thought the pick up time start whenever, but then the return day would be 5 days from the pick up time selected.

Also pushed changes to empty the cart after order.

**Comment by Xisheng0725** [comment]
> @Qihuiwang3 Was confused on whether the date limitations would be from starting at the current date, so from today and 5 days ahead are the only selectable pick up and return days. That's the version from main, which I pushed already, but originally I thought the pick up time start whenever, but then the return day would be 5 days from the pick up time selected.
> 
> Also pushed changes to empty the cart after order.

image

**Comment by Qihuiwang3** [comment]
image

**Comment by denialpan** [comment]
Sorry sorry, did not push that change, just now had to do class registration. Useeffect should be defined now

**Comment by Qihuiwang3** [comment]
> @Qihuiwang3 Was confused on whether the date limitations would be from starting at the current date, so from today and 5 days ahead are the only selectable pick up and return days. That's the version from main, which I pushed already, but originally I thought the pick up time start whenever, but then the return day would be 5 days from the pick up time selected.
> 
> Also pushed changes to empty the cart after order.

Okay, so yes, client was saying select start date whenever, and return date need to be limited to 5 days after. However, when evan was. working on this ticket, and because our backend logic - first come first serve - it would be more make sense to do 5 days a cycle (for example, what if a student reserved an equipment for a project in a month, and someone else needs to reserve the same equipment for a project in next week, and there is only 1 equipment in the storage, by doing 5 days a cycle will prevent something like this from happening), which is the current version of the emain branch. We have scheduled a meeting with the client this afternoon to discuss the time selection issue.

**Comment by denialpan** [comment]
Alright sure, that's fine, what's current pushed then in this branch matches the main one.

**Comment by Qihuiwang3** [comment]
> Alright sure, that's fine, what's current pushed then in this branch matches the main one.

Yes, just match with the main, because the time selection isn't your ticket so you don't need to worry about it. Just make sure whatever you have in ur branch match with the main. Also, for your latest commit, the cart has been empty but there is nothing shown under the available equipment drop down.

**Comment by denialpan** [comment]
You can check to see if the popup details modal works properly, am currently working on the view damage report one now.

**Comment by denialpan** [comment]
https://github.com/user-attachments/assets/f9be5d91-6f04-48d3-96f6-7427c7c03f50

Connect reservation history page with damage reports.

**A lot of database cleaning is needed for this afterwards, as some items may or may not exist when creating an order, even though the Reservation page package bundle says they do. This is due to some packages containing items that no longer exist in the database.**

As seen in the example video as well, loading may be a little slow, as for any other page too. I think this is because I may have made too many requests through debugging the backend so much that Mongo is limiting how many we can do in a time period, so API calls may load longer.

**Review by Xisheng0725 — CHANGES_REQUESTED** [review]
please don't hard code damage report, find correct damage report in damage report api and relate to the order

**Comment by mengzhuou** [comment]
A few comments here:

1. Please display the most updated record in the first row of first page.
2. All your "View Damage Report" display same modal below, which does not match with the corresponding ItemID. Please take a look at "Damage Report" page to see how they display view damage report as a reference
image

**Review by Xisheng0725 — CHANGES_REQUESTED** [review]
image
I just made one order, but in my reservation history, it show 2 order.

also, view detail modal show item id, admin didn't assign item, why student can see the item id before he got the items:

image

**Comment by denialpan** [comment]
Made it so that making order will only run once, regardless of <React.StrictMode> or not, but I am unable to test it, since I can't seem to make an order with the existing class code, as no equipment appear. 

> also, view detail modal show item id, admin didn't assign item, why student can see the item id before he got the items:

this one I don't get what you mean, since the item is already assigned to them by the database when he made an order, when the person goes to pick it up, it should be that specific item. Or at least is my thought process on it.

**Pull request merged**
