### PR TITLE
Scrum-99 : Cart confirmation page

### PR DESCRIPTION
**Pull request by denialpan**

### CODE REVIEW

**Comment by mengzhuou** [comment]
1. Remove ID for each equipment selected to the cart
2. Add quantity for available items in the reservation page, and in the cart confirmation page
4. We want to sync the styling using css instead of "style"
5. Add an alert or make checkout button not available (gray out) if cart balance is 0.

**Comment by Xisheng0725** [comment]
1. When user hover on the button, it should be pointer
2. when user select items/package the dropdown should be default open 
image
3. when user select some item, and click checkout, but when they need add something new, they click back button, the cart should not be a new cart. it should be cart with item they just select.

**Review by Xisheng0725 — CHANGES_REQUESTED** [review]
1. When user hover on the button, it should be pointer
2. when user select items/package the dropdown should be default open 
image
3. when user select some item, and click checkout, but when they need add something new, they click back button, the cart should not be a new cart. it should be cart with item they just select.

**Review by weswilson24 — APPROVED** [review]

**Comment by denialpan** [comment]
> 1. When user hover on the button, it should be pointer
> 
>     2. when user select items/package the dropdown should be default open
> 
> 
> image 3. when user select some item, and click checkout, but when they need add something new, they click back button, the cart should not be a new cart. it should be cart with item they just select.

@Xisheng0725 For now, I'll fill the cart back in the next sprint, to see if we have react-redux set up yet. If not, I'll still complete this part of the code using the current way. Buttons with cursor pointer have been added.

**Review by weswilson24 — APPROVED** [review]

**Review by Qihuiwang3 — APPROVED** [review]

**Pull request merged**
