### PR TITLE
Scrum-110: Add equipment page functionality, minor css

### PR DESCRIPTION
**Pull request by denialpan**
**MERGE scrum-109 FIRST IF NOT YET MERGED**. This branch was created based off of my local scrum-109, so if the branches are merged the other way, things may be missing...? Not sure, but just to be safe.

Equipment page functionality has been added to delete individual items and edit their repair and hide status.

Specific CSS and table appearance, like column width, has not been changed yet in anticipation for a consistent theme to be decided later on, so for now, the table will look like this:
image

**Note:** There may be what seems to be a bug with editing and saving changes for equipment if there are duplicates of the same item type and their id where changes will be reflected for multiple equipment at the same time. When the database is eventually cleaned and each item id and their item name is unique, this bug will not occur, I'm just am not sure if I should have deleted all of them in case someone else were using some of them.

### CODE REVIEW

**Review by Xisheng0725 — CHANGES_REQUESTED** [review]
please reference scrum-123 for table styling as a standard, and connect with prev page.

**Review by Qihuiwang3 — CHANGES_REQUESTED** [review]
Few things I noticed:
**Edit Mode:**
Screenshot 2024-09-28 at 11 13 14
1. Based on the design on figma, along with the comment I left on their, **repair status cannot be changed under equipment page.** This status synchronizes when the status on the damage report page change. We are working on the damage report next sprint, that means for this sprint, leave it as empty or if you prefer hardcode and change it later. 
2. **The Add New Button.** This button should only appear when you are in the edit mode. Right now it's in the non-edit mode, and the position is not right as well. It should be on the top right of the table when you are in the edit mode. 
3. **Search Bar.** When you click the box, the placeholder should be gone. 
4. **Hide Column.** It should be a dropdown instead of checking on the box. It will make user confused what does check/uncheck box means. 
5. **Please check Nina's branch about the Students page UI.** She has already created a standard UI for all of our pages that includes a table. From now on, we will use that as a reference to maintain consistency.

**Review by Qihuiwang3 — CHANGES_REQUESTED** [review]
Overall, this is much better than last time! Just a few more things I noticed:

I know I asked you to use Nina’s page as a reference, but keep in mind that sometimes you can’t replicate it exactly, especially when there are differences, like having more columns on the Equipment page than on the Students page. In the future, **please double check with the Figma design to see whether you can use the exact code for formatting or if any adjustments are needed.**
Please use this screenshot as the reference:
image
1. The Search Button, the left side of the column and the back button and the heading is not aligned. This is because Nina's table has less columns than this page. 
2. Can you make sure the title of each column is centered to the following inidivual information? All those information can aligend to the left, but i think the issue is the title is not centered. 
3. You need to adjust the size of the title, users can't see the entire heading. 
4. Similar issue to the edit mode as I mentioned above.

**Comment by denialpan** [comment]
Added initial width for the column sizes instead of all even, I saw your suggestion with centering column headers and left aligning the content, but I don't think that it looks that good, if this is what you mean.
image

**Review by Xisheng0725 — CHANGES_REQUESTED** [review]
the back button connect with wrong page, run figma design for more deatil.
the table should be shrink when change the window size. the text in each column should be center instead of left, see qihui's comments for more detail.

**Comment by mengzhuou** [comment]
image

Make sure to decrease the space here, bottom buttons are not visible on my end. 

Then make sure you resolve conflicts.

**Comment by denialpan** [comment]
> the back button connect with wrong page, run figma design for more deatil. the table should be shrink when change the window size. the contents in the table should be center instead of left, you are doing the opposite. replace N/A with Available since N/A is confused to Admin

Changed the route to SelectTask, but just for this branch you won't be able to see it since this one doesn't contain SelectTask pages. Also changed N/A to Available, sorry for taking a while to understand what you meant there, didn't notice that you added more items for those fields to be empty. 

For the centering of text, @Qihuiwang3 mentioned: 
> Can you make sure the title of each column is centered to the following inidivual information? All those information can aligend to the left, but i think the issue is the title is not centered.

which I later sent an image that I don't think looks that good, so I left that unchanged for now.

**Review by Xisheng0725 — CHANGES_REQUESTED** [review]
please clean the code, such as place all the styling in css file instead of in js file. and remove all empty space. talk with NIna to fix the edit button styling issue.

Also, if the equipment name is already in the database, the price should be show the same price when you try to add new item. the below example, if I select Camera in item name, the price should update with current Camera price since each type of equipment will have same price unless admin wnat to adjust. Item ID is require for add new equipment, if there are no item id or item name pass in the form, the add new button should be not clickable.

image


ALso, back button connect with wrong pages it should connect with below page:

image

and also need to connect both ways, which mean you also need to do when choose the equipment, it should go into your page

**Review by mengzhuou — DISMISSED** [review]
Take a look at PR-123 for student css fix as a reference: https://github.com/Qihuiwang3/JID-4121-LMCFilm/pull/50

1. Please adjust the Edit button height
image
2. Please make sure the column width are appropriate so that they display full name.
3. Add a New Euqipment popup is not showing correct css.
image

**Review by Xisheng0725 — APPROVED** [review]
good to merge, thank you!

**Review by Qihuiwang3 — APPROVED** [review]

**Pull request merged**
