### PR TITLE
Scrum 123: student page

### PR DESCRIPTION
**Pull request by mengzhuou**
1. access the page at "http://localhost:3000/Students"
2. Able to get student data, modify the role or delete it in EditMode. 
3. Able to cancel the temporary EditMode changes or Save the changes.
4. Able to search for student by Name
5. Able to get back to previous page (temp solution to go to entrance page)
6. Able to save deleted and role changes.

### CODE REVIEW

**Review by Xisheng0725 — CHANGES_REQUESTED** [review]
Styling issue talked in the zoom

**Review by Qihuiwang3 — APPROVED** [review]
All the functionalities are working.

**Review by Xisheng0725 — CHANGES_REQUESTED** [review]
the form's background color is different with the page background color, and please try to do the pagination in this sprint, since next sprint is very heavy. Also, the height of seach bar and edit button shoud be 60px

**Comment by mengzhuou** [comment]
> the form's background color is different with the page background color, and please try to do the pagination in this sprint, since next sprint is very heavy. Also, the height of seach bar, edit button, and the height of each row shoud be 60px

1. I get the page background color form Figma: #FFFDF8
2. Please confirm if we want the height of search bar and others to be 60px? It looks odd on my end. Maybe we need to consider client's need for whether they will be using Windows/Mac in the future. Not sure if this will be related. 
image

3. Added pagination using Aggridtable enriched pagination style
image

**Comment by Qihuiwang3** [comment]
The Page Size is not working correctly. When I select 20, then the page is frozen. I am not able to scroll all the way down. Also the default page size is not shown.

**Review by Xisheng0725 — APPROVED** [review]

**Pull request merged**
